#!/bin/bash
# Deploy Telegram Pay Bot on Linux VPS (Ubuntu/Debian).
# Usage:
#   curl -sSL https://raw.githubusercontent.com/YOUR_USER/YOUR_REPO/main/scripts/deploy-vps.sh | bash -s -- [GITHUB_REPO_URL] [INSTALL_DIR]
#   # or clone manually, then:
#   cd /opt/pay && chmod +x scripts/deploy-vps.sh && ./scripts/deploy-vps.sh

set -e
GITHUB_REPO="${1:-}"
INSTALL_DIR="${2:-$(pwd)}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "[*] Telegram Pay Bot — VPS deploy"
echo "[*] Install dir: $INSTALL_DIR"

# --- Clone from GitHub if URL given ---
if [ -n "$GITHUB_REPO" ]; then
  if [ ! -d "$INSTALL_DIR" ] || [ -z "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
    echo "[*] Cloning $GITHUB_REPO into $INSTALL_DIR ..."
    PARENT="$(dirname "$INSTALL_DIR")"
    if [ ! -d "$PARENT" ]; then
      sudo mkdir -p "$PARENT"
      sudo chown "$(whoami):$(whoami)" "$PARENT"
    fi
    git clone "$GITHUB_REPO" "$INSTALL_DIR"
  else
    echo "[*] Dir $INSTALL_DIR exists, skipping clone."
  fi
  PROJECT_ROOT="$INSTALL_DIR"
  cd "$PROJECT_ROOT"
else
  cd "$PROJECT_ROOT"
fi

if [ ! -f "$PROJECT_ROOT/requirements.txt" ] || [ ! -f "$PROJECT_ROOT/main.py" ]; then
  echo "[!] Not a project root (no requirements.txt or main.py). Run from repo root or pass repo URL."
  exit 1
fi

# --- System deps (Ubuntu/Debian) ---
if command -v apt-get &>/dev/null; then
  echo "[*] Installing system packages..."
  sudo apt-get update -qq
  sudo apt-get install -y -qq python3 python3-venv python3-pip git ca-certificates curl
  if ! command -v caddy &>/dev/null; then
    echo "[*] Installing Caddy..."
    sudo apt-get install -y -qq debian-keyring debian-archive-keyring
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    sudo apt-get update -qq && sudo apt-get install -y -qq caddy
  fi
fi

# --- Python venv ---
VENV_DIR="$PROJECT_ROOT/.venv"
if [ ! -d "$VENV_DIR" ] || [ ! -f "$VENV_DIR/bin/activate" ]; then
  echo "[*] Creating virtualenv..."
  python3 -m venv "$VENV_DIR"
fi
source "$VENV_DIR/bin/activate"
pip install -q -r "$PROJECT_ROOT/requirements.txt"

# --- .env ---
ENV_FILE="$PROJECT_ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "[*] Creating .env from .env.example..."
  cp "$PROJECT_ROOT/.env.example" "$ENV_FILE"
  sed -i 's/USE_POLLING=true/USE_POLLING=false/' "$ENV_FILE"
  echo ""
  echo "[!] Edit .env and set at least: BOT_TOKEN, ADMIN_IDS, WEBAPP_URL, WEBHOOK_URL, CHANNEL_IDS"
  echo "    nano $ENV_FILE"
  echo ""
  read -p "Edit .env now? [y/N] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[yY] ]]; then
    "${EDITOR:-nano}" "$ENV_FILE"
  fi
else
  grep -q 'USE_POLLING=true' "$ENV_FILE" && sed -i 's/USE_POLLING=true/USE_POLLING=false/' "$ENV_FILE" || true
fi

# --- Caddyfile from .env domain ---
get_domain() {
  local u
  u=$(grep -E '^WEBAPP_URL=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '\r')
  [ -z "$u" ] && u=$(grep -E '^WEBHOOK_URL=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '\r')
  if [ -n "$u" ]; then
    echo "$u" | sed -E 's|^https?://([^/]+).*|\1|'
  fi
}
DOMAIN=$(get_domain)
if [ -z "$DOMAIN" ]; then
  echo "[!] Could not get domain from .env (WEBAPP_URL or WEBHOOK_URL). Set them to https://your-domain.com"
else
  echo "[*] Domain: $DOMAIN"
  CADDYFILE="$PROJECT_ROOT/Caddyfile"
  {
    echo "# Generated by deploy-vps.sh"
    echo "$DOMAIN {"
    echo "    reverse_proxy 127.0.0.1:8000"
    echo "}"
  } > "$CADDYFILE"
  echo "[*] Caddyfile written: $CADDYFILE"
fi

# --- Systemd service ---
SERVICE_NAME="pay-bot"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
PYTHON_BIN="$VENV_DIR/bin/python"
MAIN_PY="$PROJECT_ROOT/main.py"

sudo tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=Telegram Pay Bot (FastAPI + Webhook)
After=network.target caddy.service

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$PROJECT_ROOT
Environment=PATH=$VENV_DIR/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=$PYTHON_BIN $MAIN_PY
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

echo "[*] Systemd unit: $SERVICE_FILE"

# --- Enable Caddy and app ---
sudo systemctl daemon-reload
sudo systemctl enable caddy 2>/dev/null || true
sudo systemctl enable "$SERVICE_NAME"
echo ""
echo "[*] Caddy will listen on 80/443 and proxy to the bot. Start services:"
echo "    sudo systemctl start caddy"
echo "    sudo systemctl start $SERVICE_NAME"
echo ""
echo "    Status:  sudo systemctl status $SERVICE_NAME"
echo "    Logs:    journalctl -u $SERVICE_NAME -f"
echo ""
read -p "Start Caddy and $SERVICE_NAME now? [Y/n] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[nN] ]]; then
  sudo systemctl restart caddy 2>/dev/null || true
  sudo systemctl start "$SERVICE_NAME"
  sleep 2
  sudo systemctl status "$SERVICE_NAME" --no-pager || true
fi
echo ""
echo "Done. Bot should be available at https://$DOMAIN (Mini App: https://$DOMAIN/mini_app/)"
