#Requires -Version 5.1
$ErrorActionPreference = 'Stop'

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not (Test-Path (Join-Path $ProjectRoot '.env'))) {
    $ProjectRoot = (Get-Location).Path
}
$EnvPath = Join-Path $ProjectRoot '.env'
$CaddyfilePath = Join-Path $ProjectRoot 'Caddyfile'
$CaddyDir = Join-Path $ProjectRoot 'caddy'
$CaddyExe = Join-Path $CaddyDir 'caddy.exe'

function Get-EnvValue {
    param([string]$Path, [string]$Key)
    $line = Get-Content $Path -Raw
    $pattern = [regex]::Escape($Key) + '\s*=\s*(.+?)(?:\r?\n|$)'
    if ($line -match $pattern) { return $Matches[1].Trim() }
    return $null
}

function Set-EnvValue {
    param([string]$Path, [string]$Key, [string]$Value)
    $content = Get-Content $Path -Raw
    $pattern = '(' + [regex]::Escape($Key) + '\s*=\s*).*'
    $replacement = "`${1}$Value"
    $newContent = $content -replace $pattern, $replacement
    if ($content -eq $newContent) {
        $newContent = $content.TrimEnd() + "`r`n$Key=$Value`r`n"
    }
    Set-Content $Path $newContent -NoNewline
}

function Get-HostFromUrl {
    param([string]$Url)
    if (-not $Url) { return $null }
    if ($Url -match '^(?:https?://)?([^/\s:]+)') { return $Matches[1] }
    return $null
}

if (-not (Test-Path $EnvPath)) {
    Write-Error '.env not found. Copy .env.example to .env and set WEBAPP_URL.'
}

$webappUrl = Get-EnvValue -Path $EnvPath -Key 'WEBAPP_URL'
$webhookUrl = Get-EnvValue -Path $EnvPath -Key 'WEBHOOK_URL'
$hostname = Get-HostFromUrl $webappUrl
if (-not $hostname) { $hostname = Get-HostFromUrl $webhookUrl }
if (-not $hostname) {
    Write-Error 'Set WEBAPP_URL or WEBHOOK_URL in .env with your domain.'
}

Write-Host ('Domain: ' + $hostname) -ForegroundColor Cyan

$CaddyVersion = '2.7.6'
$CaddyZipUrl = 'https://github.com/caddyserver/caddy/releases/download/v' + $CaddyVersion + '/caddy_' + $CaddyVersion + '_windows_amd64.zip'

if (-not (Test-Path $CaddyExe)) {
    Write-Host ('Downloading Caddy v' + $CaddyVersion + '...') -ForegroundColor Yellow
    New-Item -ItemType Directory -Force -Path $CaddyDir | Out-Null
    $zipPath = Join-Path $CaddyDir 'caddy.zip'
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $CaddyZipUrl -OutFile $zipPath -UseBasicParsing
    } catch {
        Write-Host ('Download failed: ' + $CaddyZipUrl) -ForegroundColor Red
        throw
    }
    Expand-Archive -Path $zipPath -DestinationPath $CaddyDir -Force
    Remove-Item $zipPath -Force
    Write-Host ('Caddy installed to ' + $CaddyDir) -ForegroundColor Green
} else {
    Write-Host 'Caddy already installed.' -ForegroundColor Green
}

$port = Get-EnvValue -Path $EnvPath -Key 'PORT'
if (-not $port) { $port = '8000' }
$line1 = '# Generated by setup-https.ps1'
$line2 = $hostname + ' {'
$line3 = '    reverse_proxy localhost:' + $port
$line4 = '}'
$caddyfileContent = $line1 + "`n" + $line2 + "`n" + $line3 + "`n" + $line4 + "`n"
Set-Content $CaddyfilePath $caddyfileContent -Encoding UTF8
Write-Host ('Caddyfile: ' + $CaddyfilePath) -ForegroundColor Green

$httpsWebapp = 'https://' + $hostname + '/mini_app/'
$httpsWebhook = 'https://' + $hostname
$needUpdate = $false
if ($webappUrl -ne $httpsWebapp) { Set-EnvValue -Path $EnvPath -Key 'WEBAPP_URL' -Value $httpsWebapp; $needUpdate = $true }
if ($webhookUrl -ne $httpsWebhook) { Set-EnvValue -Path $EnvPath -Key 'WEBHOOK_URL' -Value $httpsWebhook; $needUpdate = $true }
$usePolling = Get-EnvValue -Path $EnvPath -Key 'USE_POLLING'
if ($usePolling -eq 'true') {
    Set-EnvValue -Path $EnvPath -Key 'USE_POLLING' -Value 'false'
    $needUpdate = $true
    Write-Host 'USE_POLLING set to false in .env' -ForegroundColor Yellow
}
if ($needUpdate) { Write-Host '.env updated for HTTPS.' -ForegroundColor Green }

Write-Host ''
Write-Host 'Done. Next:' -ForegroundColor Cyan
Write-Host '  1. Forward ports 80 and 443 to this PC.'
Write-Host '  2. Run: .\scripts\run-with-https.ps1'
Write-Host ''
